import { DownloadItem } from "../types";

export function exportToMarkdown(url: string, title: string): string {
  const date = new Date().toLocaleDateString();
  return `# ${title}\n\n**Source:** [${url}](${url})\n**Date:** ${date}\n\n---\n\n## Content Summary\nThis page was archived via Nature Browser Ultimate. \n\n### Embedded Media Detected\n- ![Thumbnail](https://picsum.photos/seed/nature/800/400)\n\n### Full Text Extract\n[Simulated extraction of main article content goes here...]\n\n---\n*Generated by Nature Browser Ultimate*`;
}

export function simulateDownload(filename: string, content: string, type: string): DownloadItem {
  return {
    id: Math.random().toString(36).substr(2, 9),
    filename,
    url: "blob://internal",
    progress: 100,
    status: 'completed',
    size: (content.length / 1024).toFixed(1) + " KB",
    mimeType: type
  };
}

export function saveAsPDF() {
  // Real PDF export in browser
  window.print();
}
